updated NodeUpgradeStrategy.Drain to use a pointer
rancher/types pull request #1183
Opened 2020-10-05 19:18 UTC by paynejacob

https://github.com/rancher/rancher/issues/29058
https://github.com/rancher/terraform-provider-rancher2/issues/440

Allow the drain flag on the NodeUpdateStrategy struct to be nil instead of defaulting to false.

2020-10-08 13:57 UTC, superseb requested changes
This sounds like https://github.com/rancher/types/pull/1083 but there was no removal of `omitempty` in that PR, can you describe why it is removed for `Drain` and why that is different?

2020-10-12 16:29 UTC, paynejacob commented
@superseb I had removed it because I miss read the reqs I added it back in .

2020-10-12 17:24 UTC, superseb approved these changes

2020-10-15 22:14 UTC, paynejacob commented
closing in favor of https://github.com/rancher/rke/pull/2278

2020-10-15 22:14 UTC, closed without merging